// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzdgJUXJpOtW7cQSVGtxM-kumNBBXk8N0',
    appId: '1:683497843689:web:e5ae7a174232cbebb6b978',
    messagingSenderId: '683497843689',
    projectId: 'kasir-app22',
    authDomain: 'kasir-app22.firebaseapp.com',
    storageBucket: 'kasir-app22.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtmxlKtBN6uwLtVY6CDn9QaWXHaNDD2Ps',
    appId: '1:683497843689:android:7c63512431b9e33bb6b978',
    messagingSenderId: '683497843689',
    projectId: 'kasir-app22',
    storageBucket: 'kasir-app22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1t5kqGCPeU7tWoGLrJ-_AEezKlY28pSw',
    appId: '1:683497843689:ios:b7d8c94e84d9840eb6b978',
    messagingSenderId: '683497843689',
    projectId: 'kasir-app22',
    storageBucket: 'kasir-app22.firebasestorage.app',
    iosBundleId: 'com.example.kasirApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1t5kqGCPeU7tWoGLrJ-_AEezKlY28pSw',
    appId: '1:683497843689:ios:b7d8c94e84d9840eb6b978',
    messagingSenderId: '683497843689',
    projectId: 'kasir-app22',
    storageBucket: 'kasir-app22.firebasestorage.app',
    iosBundleId: 'com.example.kasirApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzdgJUXJpOtW7cQSVGtxM-kumNBBXk8N0',
    appId: '1:683497843689:web:e1e081670efeb754b6b978',
    messagingSenderId: '683497843689',
    projectId: 'kasir-app22',
    authDomain: 'kasir-app22.firebaseapp.com',
    storageBucket: 'kasir-app22.firebasestorage.app',
  );
}
